version: '3.9'
services:
  agent1:
    build:
      context: .
      dockerfile: agent/Dockerfile
    command: ["python", "-m", "agent.main"]
    environment:
      CONFIG_PATH: /app/configs/agent1/agent.yaml
    volumes:
      - ./configs:/app/configs:ro
    ports:
      - "8001:8001"
  agent2:
    build:
      context: .
      dockerfile: agent/Dockerfile
    command: ["python", "-m", "agent.main"]
    environment:
      CONFIG_PATH: /app/configs/agent2/agent.yaml
    volumes:
      - ./configs:/app/configs:ro
    ports:
      - "8002:8002"
  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    depends_on:
      - agent1
      - agent2
    command: ["python", "-m", "orchestrator.main"]
    environment:
      CONFIG_PATH: /app/configs/router.yaml
    volumes:
      - ./configs:/app/configs:ro
    ports:
      - "8101:8101"
