version: '3.9'
services:
  agent:
    build: .
    environment:
      CONFIG_PATH: /app/configs/echo.yaml
    volumes:
      - ./configs:/app/configs:ro
    ports:
      - "8000:8000"
  orchestrator:
    build: .
    depends_on:
      - agent
    command: ["python", "-m", "orchestrator.main"]
    ports:
      - "8001:8001"
