version: '3.9'
services:
  base:
    build:
      context: .
      dockerfile: base/Dockerfile
    image: nanoagentlab-base
    profiles: ["build"]

  agent1:
    build:
      context: .
      dockerfile: agent/Dockerfile
    image: nanoagentlab-agent
    depends_on:
      - base
    command: ["python", "-m", "agent.main"]
    environment:
      CONFIG_PATH: /app/configs/agent1/agent.yaml
    volumes:
      - ./configs:/app/configs:ro
    ports:
      - "8001:8001"

  agent2:
    image: nanoagentlab-agent
    depends_on:
      - agent1
    command: ["python", "-m", "agent.main"]
    environment:
      CONFIG_PATH: /app/configs/agent2/agent.yaml
    volumes:
      - ./configs:/app/configs:ro
    ports:
      - "8002:8002"

  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    image: nanoagentlab-orchestrator
    depends_on:
      - agent1
      - agent2
    command: ["python", "-m", "orchestrator.main"]
    environment:
      CONFIG_PATH: /app/configs/router.yaml
    volumes:
      - ./configs:/app/configs:ro
    ports:
      - "8101:8101"
